// Re-export shared types with legacy names for components that haven't been updated yet
export type {
  BaseUser as User,
  BaseProject as Project,
  BaseNote as Note,
  BaseTodo as Todo,
  BaseDevLogEntry as DevLogEntry,
  BaseFeature as Doc, // Legacy alias for backward compatibility
  BaseTeamMember as TeamMember,
  BaseProjectInvitation as ProjectInvitation,
  BaseNotification as Notification,
  InviteUserData,
  // Export the original Base types for API files
  BaseProject,
  BaseNote,
  BaseTodo,
  BaseDevLogEntry,
  BaseFeature,
  ProjectResponse,
  CreateProjectData,
  UpdateProjectData,
  CreateNoteData,
  UpdateNoteData,
  CreateTodoData,
  UpdateTodoData,
  CreateDevLogData,
  UpdateDevLogData,
  CreateFeatureData,
  UpdateFeatureData,
  CreateRelationshipData,
  RelationshipType,
  FeatureRelationship,
  AuthResponse,
  LoginData,
  RegisterData
} from '../../../shared/types';